version: '3'
services:
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./front:/app
    depends_on:
      - back

  back:
    build:
      context: ./back/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app