version: '3'
services:
  front:
    build:
      context: ./
      dockerfile: ./front/Dockerfile
      args:
        PORT: ${FRONT_DOCKER_EXPOSED_PORT:-80}
        HOST: nuxt-app
        API_HOST: http://localhost:${API_DOCKER_EXPOSED_PORT:-3000}
    ports:
      - ${FRONT_DOCKER_EXPOSED_PORT:-80}:3000
    command:
      - /bin/sh
      - -c
      - |
        apk add --update nodejs npm
        cd app
        npm run dev
    volumes:
      - ./front:/app
      # - ./front/assets:/app/assets
      # - ./front/components:/app/components
      # - ./front/layouts:/app/layouts
      # - ./front/middleware:/app/middleware
      # - ./front/pages:/app/pages
      # - ./front/plugins:/app/plugins
      # - ./front/services:/app/services
      # - ./front/static:/app/static
      # - ./front/store:/app/store
    networks:
      - krop-network
    depends_on:
      - back

  back:
    build:
      context: ./back/
      dockerfile: Dockerfile
    ports:
      - "${API_DOCKER_EXPOSED_PORT:-3000}:3000"
    volumes:
      - ./back:/app
    networks:
      - krop-network
networks:
  krop-network:
    driver: bridge